### ISSUE TITLE
Implement volume control

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#56]
Hi Gilbert 

If you have time  :)

Regards 
Marc

**Comment by aidan-g** [comment]
Implemented since ce40563f3e95e1ec43a56baf0360d6724c71134a.
It works for DirectSound and WASAPI (not in exclusive mode) outputs.

![VolumeSlider](https://user-images.githubusercontent.com/13859177/78838665-92c85000-79ee-11ea-8d39-977cfb310228.PNG)

The styling needs improvment but I'm not so good at that kind of thing.
