### ISSUE TITLE
Drag and drop between two playlists

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#72]
When you are into a playlist and want to drag and drop a song to another playlist, FoxTunes create a new empty playlist.

**Comment by aidan-g** [comment]
Partial implementation since 134cda9c71c86d5f63ef7125b5e4a8f977ea7980.

![CreatePlaylistFromTracks](https://user-images.githubusercontent.com/13859177/86180367-e5b03000-bb23-11ea-9ffd-b5d627c9c692.gif)

Only creating a new playlist is working, we need a drag-over handler for the tab headers so an existing playlist can be amended.

**Comment by aidan-g** [comment]
Implemented since 7cd608d5b8285f85c5d88b6da45a3641d9ec9050
